### ISSUE TITLE
Build failure / Haddock issues / Stackage inclusion ?

### ISSUE THREAD

**Issue by psibi** [markandrus/twiml-haskell#9]
Right now, I cannot use something like this in my stack.yaml file and make the build pass:

```
- location:
    git: git@github.com:markandrus/twiml-haskell.git
    commit: fd12ac0457673f21b0158d3136c2f4555ae4c61c
  extra-dep: true
```

The reason is because the repository cannot be built without running
the `make` command (which needs to be documented by the way!). This
has to be fixed by modifying `Setup.hs` and doing a custom build there.

Also, I think that's the reason Hackage's haddock isn't working. (eg:
https://hackage.haskell.org/package/twiml-0.2.0.1/docs/Text-XML-Twiml-Internal.html)

Also, if you can maintain this (and also twilio package) in Stackage, it would be nice!
